version: '3'

services:
  db:
    image: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./dbdata/init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secribe_su_contrasena
      MYSQL_DATABASE: price_comparison
    networks:
      - mynet
  web:
    networks:
      - mynet
    build: ./app
    ports:
      - "8080:5000"
    depends_on:
      - db
    command: sh -c 'sleep 30 && python3 insert_data.py && python3 app.py'

networks:
  mynet:
    driver: bridge